space_id = ""  # Your Cobot space ID
api_base = "https://api.cobot.me"
access_token = ""  # Your Cobot API access token
default_resource_id = ""  # Optional: Default resource ID to use when none is specified
data_dir = "~/.local/share/cobot"  # Directory for storing booking history and other data
monitor_days_ahead = 30  # Number of days to look ahead when monitoring bookings
log_file = "logs/cobot.log"  # Log file path (relative to data_dir, will be created in ~/.local/share/cobot/logs/cobot.log)
telegram_bot_token = ""  # Your Telegram bot token from BotFather
telegram_chat_id = ""  # Your Telegram chat ID where messages will be sent
